version: "3.8"

services:
  postgres:
    image: ankane/pgvector:latest
    container_name: pgvector-dev
    restart: always
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgvector_data_dev:/var/lib/postgresql/data
    networks:
      - dev_network

volumes:
  pgvector_data_dev:

networks:
  dev_network:
